version: "3.8"

services:
  db:
    container_name: db
    image: postgres:15.2
    environment:
      - POSTGRES_USER=db
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5532:5432"
    networks:
      - test_network
    restart: on-failure
  pgbouncer:
    image: rmccaffrey/pgbouncer:latest
    container_name: 'pgbouncer'
    environment:
      - DATABASE_URL=postgres://db:password@db:5432/db
      - POOL_MODE=transaction
      - MAX_DB_CONNECTIONS=100
      - DEFAULT_POOL_SIZE=40
      - AUTH_TYPE=scram-sha-256
    depends_on:
      - db
    networks:
      - test_network
    restart: on-failure
  djangoapp:
    build: ./docker/app
    container_name: djangoapp
    depends_on:
      - db
      - pgbouncer
    ports:
      - "8001:8000"
    image: djangoapp/server
    networks:
      - test_network
    restart: on-failure
    environment:
      - DJANGO_SETTINGS_MODULE=testpgbouncer.settings
      - DATABASE_URL=postgres://db:password@pgbouncer:5432/db
    command: |
      /bin/bash -c "
        python manage.py collectstatic --noinput
        set -xe
        daphne -b 0.0.0.0 -p 8000 testpgbouncer.asgi:application
      "

networks:
  test_network:

volumes:
  db:
